### PR TITLE
Remove snapshot, remove incorrect import

### LINKED ISSUE #198: mvn clean install errors
Error is this:
```
$ mvn clean install
...
[ERROR] Failed to execute goal on project ctk-domain: Could not resolve dependencies for project org.ga4gh:ctk-domain:jar:0.6.0a3: Could not find artifact org.apache.bcel:bcel:jar:6.0-SNAPSHOT in Apache (http://repository.apache.org/snapshots) -> [Help 1]
...
```

Apache has possibly stopped hosting the artifact?

### PR DESCRIPTION
**Pull request by david4096**
closes #198 @dcolligan :)

### CODE REVIEW

**Comment by dcolligan** [comment]
Great. +1

File: cts-java/src/test/java/org/ga4gh/cts/api/Utils.java [hunk 1]
```diff
@@ -11,7 +11,6 @@
 import ga4gh.AlleleAnnotations.VariantAnnotationSet;
 import ga4gh.Reads.*;
 import ga4gh.ReadServiceOuterClass.*;
-import ga4gh.Reads.ReadGroup.Program;
```
Comment (bwalsh) [inline cts-java/src/test/java/org/ga4gh/cts/api/Utils.java]: I needed to add

Comment (david4096) [inline cts-java/src/test/java/org/ga4gh/cts/api/Utils.java]: Do you have the `import ga4gh.Metadata.*;`?
